### ISSUE TITLE
 how to find minimal enclosed circle

### ISSUE THREAD

**Issue by llf1234** [HzDmS/gaze_redirection#2]
hi，i am very appreciate for your excellent work，the method of solving minimal enclosed circle has confused me a lot，can your explain it with more detail。

**Comment by HzDmS** [comment]
Hi, it is a function named 'cv2.minEnclosingCircle' in opencv. For more information, please refer to the API document of opencv, https://docs.opencv.org/3.1.0/d3/dc0/group__imgproc__shape.html#ga8ce13c24081bbc7151e9326f412190f1.

**Comment by HzDmS** [comment]
> hi，i am very appreciate for your excellent work，the method of solving minimal enclosed circle has confused me a lot，can your explain it with more detail。

Hi, it is a function named 'cv2.minEnclosingCircle' in opencv. For more information, please refer to the API document of opencv, https://docs.opencv.org/3.1.0/d3/dc0/group__imgproc__shape.html#ga8ce13c24081bbc7151e9326f412190f1.

**Comment by llf1234** [comment]
thanks a lot，recently i train a model with your provided code and data，i find the color of generated eyes is not always consistent with the original input（test on other pic which is not in columbia dataset），when i cancel all instance normalization layer in generator， the color of generated eyes become approximate consitent with the original input？ did you pay attention on this phenomenon.
